# Generated by Django 3.2.4 on 2021-06-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibration_y', models.FloatField()),
                ('pressure_6h_mean', models.FloatField()),
                ('temperature_6h_std', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'predicts',
            },
        ),
    ]
